//INDEX DE JS
//ACTION LOGIN
export const PETITION_LOGIN = "PETITION_LOGIN";
export const PETITION_EXIT_LOGIN = "PETITION_EXIT_LOGIN";

//ACTION FORM
export const PETITION_FORM_PHOTO='PETITION_FORM_PHOTO';
export const PETITION_FORM_RESET_PHOTO='PETITION_FORM_RESET_PHOTO';
export const PETITION_SAVE_DATE='PETITION_SAVE_DATE';
export const PETITION_SAVE_TIME_START='PETITION_SAVE_TIME_START';
export const PETITION_SAVE_DISABLE='PETITION_SAVE_DISABLE'