//INDEX DE JS
//ACTION LOGIN
export const PETITION_LOGIN = "PETITION_LOGIN";
export const PETITION_EXIT_LOGIN = "PETITION_EXIT_LOGIN";

//ACTION FORM
export const PETITION_FORM_PHOTO='PETITION_FORM_PHOTO';
export const PETITION_FORM_RESET_PHOTO='PETITION_FORM_RESET_PHOTO';
export const PETITION_SAVE_DATE='PETITION_SAVE_DATE';
export const PETITION_SAVE_TIME_START='PETITION_SAVE_TIME_START';
export const PETITION_SAVE_DISABLE='PETITION_SAVE_DISABLE';
export const PETITION_SAVE_SELECT='PETITION_SAVE_SELECT';
export const PETITION_RESET_DATA='PETITION_RESET_DATA';

//ACTION INFORMATION
export const PETITION_DISABLE_CARD='PETITION_DISABLE_CARD';
export const PETITION_ARRAY_INFORMATION='PETITION_ARRAY_INFORMATION';

//
export const PETITION_BACK= 'PETITION_BACK';

//
export const PETITION_RESET_USER='PETITION_RESET_USER'